### ISSUE TITLE
OslcQueryResult returns no members

### ISSUE THREAD

**Issue by jamsden** [eclipse/lyo.client#23] opened 2019-01-23 20:28 UTC
The JAX-RS 2.0/Jersey implementation of oslc-java-client does not return any members when running the GenericCMSample.java program. When initializeRdf() attempts to get the membersResource, its searching the refModel for a resource whose subject is the query.getCapabilityUrl(). When invoked from GenericCMSample, that URL looks like http://192.168.1.140:8080/OSLC4JChangeManagement/services/changeRequests. However, examining the content of the Jena rdfModel, the subject URIs look like http://localhost:8080/OSLC4JChangeManagement/services/changeRequests, so these aren't matching and the membersResource is null.

All the URLs in the ServiceProvider have http://192.168.1.140:8080, so that's why the queryCapability URI starts with http://192.168.1.140:8080.

**Comment by berezovskyi** [comment] 2019-01-23 22:08
Interesting. I believe the mismatch of the URLs to be the fault of the server. I would start by fixing the consistency of the server response and then handling this case as a more advanced one (fool-proof, so to speak). Could you point me to the right branch and the module you run as a server, please? Or is it an OSLC server that is built in into a product? I can try to investigate.

--
/Andrew

23 jan. 2019 kl. 21:28 skrev Jim Amsden <notifications@github.com<mailto:notifications@github.com>>:


The JAX-RS 2.0/Jersey implementation of oslc-java-client does not return any members when running the GenericCMSample.java program. When initializeRdf() attempts to get the membersResource, its searching the refModel for a resource whose subject is the query.getCapabilityUrl(). When invoked from GenericCMSample, that URL looks like http://192.168.1.140:8080/OSLC4JChangeManagement/services/changeRequests. However, examining the content of the Jena rdfModel, the subject URIs look like http://localhost:8080/OSLC4JChangeManagement/services/changeRequests, so these aren't matching and the membersResource is null.

All the URLs in the ServiceProvider have http://192.168.1.140:8080, so that's why the queryCapability URI starts with http://192.168.1.140:8080.

**Comment by jamsden** [comment] 2019-01-23 22:19
I'm guessing that if you don't use localhost (which is always a bad practice), it will work. I'll try that tomorrow. Busy tonight.

**Comment by jamsden** [comment] 2019-01-23 22:24
oslc4j-cm-sample on master is the server I used. GenericCMSample is sample client application. lyo.core and lyo.client are on branch F_jax-rs-2.0-post2.4.0.

**Comment by berezovskyi** [comment] 2019-01-24 10:21
@jamsden Jad's right.

When we worked on the `OSLC4JUtils.set*` methods, my preference was to crash the server so that the developer would be forced to fix this but you guys outvoted me. The problem is that the hostname should never be guessed but instead configured, especially in today's containerised world. The implementation left in the code is the one that relies on the [PTR records](https://en.wikipedia.org/wiki/Reverse_DNS_lookup#IPv4_reverse_resolution) being set correcly in the DNS. So, this would not only fail on localhost, but also behind load balancers or service meshes of some kind, behind enterprise firewalls etc.

Setting the two values as suggested by Jad should fix the problem.

**Comment by berezovskyi** [comment] 2019-01-30 14:06
Do you mean that the adaptor still tries to figure out its canonical hostname despite you having set the URI and the path through OSLC4JUtils beforehand?

**Comment by jamsden** [comment] 2019-01-30 14:35
No, it's using ` InetAddress.getLocalHost().getCanonicalHostName();` to get the host name to use in creating the baseUri. I have't looked at this yet. Trying to get SSLContext to work in the oslc4j-client. Many hours lost on this.

**Comment by jamsden** [comment] 2019-01-30 20:45
In lyo.rio-oslc4j, oslc4j-cm-sample, ServletListener.contextInitializer, I added the following calls to set the base URI and servlet URI pattern for use by oslc4j-core
```
OSLC4JUtils.setPublicURI(baseUrl);
OSLC4JUtils.setServletPath(servletUrlPattern);
```
I made sure the host name is being calculated by `InetAddress.getLocalHost().getCanonicalHostName();` wasn't an IP address, and set these two system properties on the oslc4j-cm-server run configuration:
```
-Dorg.eclipse.lyo.oslc4j.client.registryuri=http://localhost:8080/OSLC4JRegistry/catalog/singleton
-Dorg.eclipse.lyo.oslc4j.client.uiuri=http://localhost:8080/OSLC4JUI
```
But the ServiceProviderCatalog URI is still being calculated to use an IP address:
```
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:dcterms="http://purl.org/dc/terms/"
    xmlns:oslc_data="http://open-services.net/ns/servicemanagement/1.0/"
    xmlns:oslc="http://open-services.net/ns/core#"
    xmlns:oslc_scm="http://open-services.net/ns/scm#"
    xmlns:oslc_cm="http://open-services.net/ns/cm#"
    xmlns:oslc_qm="http://open-services.net/ns/qm#"
    xmlns:oslc_rm="http://open-services.net/ns/rm#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:foaf="http://xmlns.com/foaf/0.1/">
    <oslc_cm:ChangeRequest>
        <oslc_cm:inprogress rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean"
    >true</oslc_cm:inprogress>
        <dcterms:modified rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime"
    >2019-01-30T20:34:37.645Z</dcterms:modified>
        <dcterms:title rdf:parseType="Literal">Need to update the database schema to reflect the data model changes</dcterms:title>
        <oslc:serviceProvider rdf:resource="http://192.168.1.140:8080/OSLC4JRegistry/serviceProviders/2"/>
        <oslc_cm:closed rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean"
    >false</oslc_cm:closed>
        <oslc_cm:severity>Unclassified</oslc_cm:severity>
    </oslc_cm:ChangeRequest>
</rdf:RDF>
```
I've perhaps exhausted my ability to fix this. Jad?

**Comment by jadelkhoury** [comment] 2019-01-30 22:41
To start with, is the OslcQueryResult working as expected now? This was the original problem. The latest rdf/xml is about the catalog, which I assume is another issue. Right?

@jamsden I can help debug, but could you possible share/push the code, so I can reproduce here?

**Comment by jamsden** [comment] 2019-01-31 12:20
Jad,
I think the problem is that some URLs have the IP address and some have 
the localhost name, and therefore don't match, causing the query to return 
no results.

I'll push code today.

Thanks for the help - I'm pretty buried in the client and spending too 
much time on it. 


Jim Amsden, Senior Technical Staff Member
OSLC and Linked Lifecycle Data
919-525-6575

**Comment by jadelkhoury** [comment] 2019-01-31 21:39
my usual maven goal jetty:run

**Comment by jadelkhoury** [comment] 2019-01-31 23:04
An update:
I moved on by simply commenting out that RegistrationTask. I believe it relates to some client code, so maybe not relevant.
I have some minor fixes when it comes to the publicUri, and servletUri settings. But that's details for now.

To proceed, I would need (@jamsden ) the client that you are using to produce this errors.

I am testing using a browser, and from the front page of the server at http://localhost:8086/OSLC4JChangeManagement/
1. The catalog is located at http://localhost:8086/OSLC4JRegistry/catalog/singleton
2. The query on ChangeRequests (http://localhost:8086/OSLC4JChangeManagement/services/changeRequests) is leading to an empty resultSet.

So I can't really reproduce the 2 problems above. I am not sure how to deal with this oslc4j-registery stuff.

**Comment by jadelkhoury** [comment] 2019-01-31 23:15
So, I now pushed a small change that I hope fixes the QueryResult problem.
But it is still the case that the server returns 0 results. How can you make it produce more?


1. 
```
OSLC4JUtils.setPublicURI(baseUrl);
OSLC4JUtils.setServletPath(servletUrlPattern);
```
The baseUri should not contain the servletUrlPattern, since you were otherwise ending up with "services/services" in the rdf:about of the oslc:ResponseInfo, which is certainly NOT the orignal request URL.

2. The client making a query request MUST make sure it uses the same URI/L as that of baseUrl. that is, I don't think we can handle a request to http://192.168.1.140:8080/..., when the  oslc:ResponseInfo is returned as "http://localhost:8080". The query libray is not that smart.

**Comment by jadelkhoury** [comment] 2019-01-31 23:44
>The registrationtask you have commented out generated some CM resources.
No! That only registers the ServiceProviders (to the oslc4j-registery is my guess). But it is odd, since even when I comment out this task, I still get the catalog to produce 1 SP.

**Comment by jadelkhoury** [comment] 2019-01-31 23:48
Analysis:
oslc4j-registery has its own servletListener, and hence needs to set its own publichURI.
For some reason, when it does `String publicURI = OSLC4JUtils.getPublicURI();`, the result is "null". This causes its to default to some "http://localhost:8080/OSLC4JRegistry/"

So, I just need to work out how to make the 2 servlets share the same result upon calling OSLC4JUtils.getPublicURI(), and we should be fine.

Alternatevly, should we remove this registery stuff?

**Comment by jadelkhoury** [comment] 2019-01-31 23:52
OSLC4JUtils.get/setPublicURI() controls this static attribute, which is initilised through a system property.
`private static String publicURI = System.getProperty(OSLC4JConstants.OSLC4J_PUBLIC_URI);`

Would oslc4j-cm-sample and oslc4j-registery share the same class (and class attributes) OSLC4JUtils ?

**Comment by berezovskyi** [comment] 2019-02-01 02:21
Jim, with my fixes to the POM files I get the following error when trying to run the generic CM sample:

```
... org.eclipse.lyo.client.oslc.samples.GenericCMSample -url https://localhost:8080/OSLC4JRegistry/catalog/1 -providerTitle "OSLC Lyo Change Management Service Provider"
 INFO [main] (GenericCMSample.java:85) - Initialising OSLC Client
 INFO [main] (GenericCMSample.java:89) - Looking up Service Provider by URI=https://localhost:8080/OSLC4JRegistry/catalog/1 and title='OSLC Lyo Change Management Service Provider'
ERROR [main] (GenericCMSample.java:144) - Unknown error
org.apache.wink.client.ClientRuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at org.apache.wink.client.internal.ResourceImpl.invoke(ResourceImpl.java:241)
	at org.apache.wink.client.internal.ResourceImpl.invoke(ResourceImpl.java:189)
	at org.apache.wink.client.internal.ResourceImpl.invokeNoException(ResourceImpl.java:181)
	at org.apache.wink.client.internal.ResourceImpl.get(ResourceImpl.java:311)
	at org.eclipse.lyo.client.oslc.OslcClient.getResource(OslcClient.java:268)
	at org.eclipse.lyo.client.oslc.OslcClient.getResource(OslcClient.java:204)
	at org.eclipse.lyo.client.oslc.OslcClient.lookupServiceProviderUrl(OslcClient.java:469)
	at org.eclipse.lyo.client.oslc.samples.GenericCMSample.main(GenericCMSample.java:91)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at org.apache.wink.client.internal.handlers.httpclient.ApacheHttpClientConnectionHandler.handle(ApacheHttpClientConnectionHandler.java:90)
	at org.apache.wink.client.internal.handlers.HandlerContextImpl.doChain(HandlerContextImpl.java:52)
	at org.apache.wink.client.internal.handlers.AcceptHeaderHandler.handle(AcceptHeaderHandler.java:79)
	at org.apache.wink.client.internal.handlers.HandlerContextImpl.doChain(HandlerContextImpl.java:52)
	at org.apache.wink.client.internal.ResourceImpl.invoke(ResourceImpl.java:228)
	... 7 more
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at org.apache.wink.client.internal.handlers.httpclient.ApacheHttpClientConnectionHandler.processRequest(ApacheHttpClientConnectionHandler.java:116)
	at org.apache.wink.client.internal.handlers.httpclient.ApacheHttpClientConnectionHandler.handle(ApacheHttpClientConnectionHandler.java:87)
	... 11 more
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:553)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.apache.wink.client.internal.handlers.httpclient.ApacheHttpClientConnectionHandler.processRequest(ApacheHttpClientConnectionHandler.java:113)
	... 12 more

Process finished with exit code 0
```

**Comment by berezovskyi** [comment] 2019-02-01 17:17
@jamsden @jadelkhoury I forgot to ask a baseline question: does the setup work well on the JAX-RS 1.1 & Wink?

**Comment by jamsden** [comment] 2019-02-01 17:59
I have run oslc4j-cm-sample under both Wink and JAX-RS versions of oslc-core, and with both client implementations. I don't think its bug free, but I got it working to the point that at least it would create a service provider catalog and execute some requests - mostly what I needed to do the initial development on oslc4j-client. 

Let's get some of the known issues out of the way - baseURI, servletURI, annotation inheritance, etc., then I'll hopefully have a oslc4j-client working well enough to help with the testing.

**Comment by jadelkhoury** [comment] 2019-02-01 20:02
@berezovskyi are you working on this for now? I thought I can continue from where I left yesterday, especially after what you explained this afternoon.
But happy to leave it for you if you insist.

**Comment by berezovskyi** [comment] 2019-02-01 21:08
I consider the issue fixes, please check and close it @jamsden .

**Comment by jamsden** [comment] 2019-02-01 21:31
What changes did you make to what repos on what branch? Sorry I got lost in all the issues we're covering

**Comment by berezovskyi** [comment] 2019-02-01 22:14
I have made changes to:

- master@client (GenericCMSample)
- master@rio (oslc4j-cm-sample)
- master@server (registry)

**Comment by jamsden** [comment] 2019-02-05 15:03
In OslcQuery.applyQueryParams and applyPagination, WebTarget.queryPath returns a new instance of WebTarget, it doesn't add the query parameter to the target WebTarget. So all OSLC queries were being executed with no query parameters.

**Comment by berezovskyi** [comment] 2019-02-05 17:05
Hmm okay, but there are some members returned, right? If that's a separate issue, let's open another issue for this?

**Comment by jamsden** [comment] 2019-02-05 17:49
Yes, every OSLC query returned all members. I think this can be closed now.

**Closed** 2019-02-05 18:39 UTC
