### ISSUE TITLE
json-ld support fails if server also includes the OSLC client library

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo.client#83] opened 2020-04-09 09:13 UTC
I am duplicating [the issue from lyo.core](https://github.com/eclipse/lyo.core/issues/132), since I now realize maybe the problem (and solution) is to be handled by lyo.client.

**Comment by berezovskyi** [comment] 2020-04-09 15:33
Duplicate of https://github.com/eclipse/lyo.client/issues/85

**Closed by berezovskyi** 2020-04-09 15:33 UTC
